apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ai-product-catalog-svc
  labels:
    app.kubernetes.io/name: ai-product-catalog-chatbot-component
    app.kubernetes.io/part-of: ai-product-catalog-app
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"ai-product-catalog-svc-deploy"}]'
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: "ai-product-catalog"
    argocd/app-name: ai-product-catalog
    argocd/instance-name: 'argoInstance'
    quay.io/repository-slug: 'ai-product-catalog/svc'
  tags:
    - java
    - maven
  links:
    - url: https://ai-product-catalog-svc-ai-product-catalog-prod.apps.ocpbm.home.glroland.com/
      title: Prod
      icon: web
    - url: https://console-openshift-console.apps.ocpbm.home.glroland.com/k8s/ns/aij/deployments/ai-product-catalog-svc
      title: Deployment
      icon: web
    - url: 'https://devspaces.apps.ocpbm.home.glroland.com/dashboard/#/load-factory?url=https://github.com/glroland/ai-product-catalog.git'
      title: 'Code in DevSpaces'
      icon: catalog
      type: ide
spec:
  type: service
  lifecycle: production
  owner: user:default/glroland
  system: ai-product-catalog-system
  providesApis:
    - ai-product-catalog-api
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ai-product-catalog-system
  tags:
    - backstage
    - openshift
spec:
  owner: user:default/glroland
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ai-product-catalog-api
  description: API surface used for AI-enabled product search and customer chat capabilities
  links:
    - url: https://backstage-developer-hub-rhdh-operator.apps.ocpbm.home.glroland.com/swagger-ui/index.html
      title: Swagger UI
      icon: web
    - url: https://raw.githubusercontent.com/glroland/ai-product-catalog/main/ai-product-catalog-svc/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: user:default/glroland
  system: ai-product-catalog-system
  definition:
    $text: https://github.com/glroland/ai-product-catalog/blob/main/catalog/ai-product-catalog-svc/openapi.yaml

