apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: customer-chatbot
  description: "Simple chatbot for the AI Product Catalog"
  labels:
    app.kubernetes.io/name: customer-chatbot-component
    app.kubernetes.io/part-of: ai-product-catalog-app
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"customer-chatbot-deploy"}]'
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: "ai-product-catalog"
    argocd/app-name: ai-product-catalog
    argocd/instance-name: 'argoInstance'
    quay.io/repository-slug: 'ai-product-catalog/chatbot'
  links:
    - url: https://ai-product-catalog-chatbot-ai-product-catalog-prod.apps.ocpprod.home.glroland.com/
      title: Prod
      icon: web
    - url: 'https://devspaces.apps.ocpprod.home.glroland.com/dashboard/#/load-factory?url=https://github.com/glroland/ai-product-catalog.git'
      title: 'Code in DevSpaces'
      icon: catalog
      type: ide
  tags:
    - python
    - ai
    - llm
  dependsOn:
    - component:ai-product-catalog-svc
  consumesApis:
    - ai-product-catalog-api
spec:
  type: service
  lifecycle: production
  owner: user:default/glroland
  system: ai-product-catalog-system
