apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-product-catalog.fullname" . }}
  labels:
    {{- include "ai-product-catalog.labels" . | nindent 4 }}
immutable: false
data:
  OPENAI_BASEURL: "http://ocpwork:11434/v1"
  OPENAI_MODEL: "llama3.1"
  OPENAI_APIKEY: "nokey"
