apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-product-catalog.fullname" . }}
  labels:
    {{- include "ai-product-catalog.labels" . | nindent 4 }}
immutable: false
data:
  OPENAI_BASEURL: "http://ocpwork:11434/v1"
  OPENAI_MODEL: "llama3.2"
  OPENAI_APIKEY: "nokey"
  PRODUCT_DB_CONN_STRING: "host={{ .Release.Name }}-db-primary port=5432 dbname=ai_product_catalog user=ai_product_catalog password=ai_product_catalog123 connect_timeout=30"
