apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  finalizers:
    - postgres-operator.crunchydata.com/finalizer
  name: {{ include "ai-product-catalog.fullname" . }}
  labels:
    app.kubernetes.io/part-of: "{{ .Release.Name }}-ai-product-catalog"
    {{- include "ai-product-catalog.labels" . | nindent 4 }}
spec:
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      name: instance1
      replicas: 1
  port: 5432
  postgresVersion: 16
  databaseInitSQL:
    key: create_tables.sql
    name: {{ include "ai-product-catalog.fullname" . }}-init-sql
  service:
    type: ClusterIP
  users:
    - name: postgres
    - name: ai_product_catalog
      databases:
        - ai_product_catalog
      options: 'SUPERUSER'
