create table categories
(
	category_id integer primary key generated by default as identity,
	category_desc varchar(50)
);

create table brands
(
	brand_id integer primary key generated by default as identity,
	brand_desc varchar(50)
);

create table products
(
  product_id integer primary key generated by default as identity,
  sku varchar(50) not null,
  brand_id integer not null,
  product_name varchar(100) not null,
  product_desc varchar(500) not null,
  size varchar(200),
  msrp float,
  category_id integer not null,
  
  CONSTRAINT fk_category
      FOREIGN KEY(category_id) 
        REFERENCES categories(category_id),
  
  CONSTRAINT fk_brand
      FOREIGN KEY(brand_id) 
        REFERENCES brands(brand_id)
);
