apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: storefront-svc
  description: "Virtual Storefront API"
  labels:
    app.kubernetes.io/name: storefront-svc-component
    app.kubernetes.io/part-of: storefront-svc-app
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"storefront-svc-deploy"}]'
    jenkins.io/job-full-name: "default:ai-product-catalog/ai-product-catalog"
  links:
    - url: 'https://devspaces.apps.ocpbm.home.glroland.com/dashboard/#/load-factory?url=https://github.com/glroland/ai-product-catalog.git'
      title: 'Code in DevSpaces'
      icon: catalog
      type: ide
    - title: OpenShift AI
      icon: chat
      url: https://rhods-dashboard-redhat-ods-applications.apps.ocpbm.home.glroland.com/projects
  tags:
    - python
    - ai
    - llm
    - rest
spec:
  type: service
  lifecycle: experimental
  owner: user:default/glroland
