apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: storefront-svc
  description: "Virtual Storefront API"
  labels:
    app.kubernetes.io/name: storefront-svc-component
    app.kubernetes.io/part-of: storefront-svc-app
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"storefront-svc-deploy"}]'
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: "ai-product-catalog"
    argocd/app-name: ai-product-catalog
    argocd/instance-name: 'argoInstance'
    quay.io/repository-slug: 'ai-product-catalog/chatbot'
  links:
    - url: https://ai-product-catalog-storefront-svc-ai-product-catalog-prod.apps.ocpprod.home.glroland.com/
      title: Prod
      icon: web
    - url: 'https://devspaces.apps.ocpbm.home.glroland.com/dashboard/#/load-factory?url=https://github.com/glroland/ai-product-catalog.git'
      title: 'Code in DevSpaces'
      icon: catalog
      type: ide
    - title: OpenShift AI
      icon: chat
      url: https://rhods-dashboard-redhat-ods-applications.apps.ocpprod.home.glroland.com/projects
  tags:
    - python
    - ai
    - llm
    - rest
spec:
  type: service
  lifecycle: production
  owner: user:default/glroland
