apiVersion: v1
kind: Service
metadata:
  name: {{ include "storefront-svc.fullname" . }}
  labels:
    {{- include "storefront-svc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Cluster
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
      protocol: TCP
  sessionAffinity: None
  selector:
    {{- include "storefront-svc.selectorLabels" . | nindent 4 }}
