apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-product-catalog.fullname" . }}
  labels:
    {{- include "ai-product-catalog.labels" . | nindent 4 }}
data:
  application.properties: |-
    spring.application.name=ai-product-catalog

    # Default Chat Model
    ai-product-catalog.default-chat-model={{ .Values.global.appconfig.inferenceEngine }}

    # Default Model Values (applied to all)
    ai-product-catalog.max-tokens=100
    ai-product-catalog.temperature=0.1
    ai-product-catalog.top-p=1.0
    ai-product-catalog.timeout-seconds=300

    # Embedding Model Configuration
    ai-product-catalog.embedding-model=sentence-transformers/all-mpnet-base-v2
    ai-product-catalog.hf-api-key=${HF_TOKEN}

    # Agent w/Tool Assist Model Configuration 
    ai-product-catalog.{{ .Values.global.appconfig.inferenceEngine }}.inference-endpoint={{ .Values.global.appconfig.inferenceUrl }}
    ai-product-catalog.{{ .Values.global.appconfig.inferenceEngine }}.api-key=no-key-needed
    ai-product-catalog.{{ .Values.global.appconfig.inferenceEngine }}.agent-model-name={{ .Values.global.appconfig.inferenceModel }}
    ai-product-catalog.{{ .Values.global.appconfig.inferenceEngine }}.embedding-model={{ .Values.global.appconfig.inferenceModel }}
    #ai-product-catalog.{{ .Values.global.appconfig.inferenceEngine }}.embeddings-dimensions=384

    # Database Configuration
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.datasource.username=ai_product_catalog
    spring.datasource.password=ai_product_catalog123
    spring.datasource.url=jdbc:postgresql://tools.home.glroland.com:5432/ai_product_catalog

    # File Upload Config
    spring.servlet.multipart.file-size-threshold=2KB
    spring.servlet.multipart.max-file-size=200MB
    spring.servlet.multipart.max-request-size=215MB
    server.connection-timeout=5000

    # Logging Configuration
    logging.level.com.glroland=DEBUG
    langchain4j.open-ai.chat-model.log-requests=true
    langchain4j.open-ai.chat-model.log-responses=true
    logging.level.dev.langchain4j=INFO
    #logging.level.dev.ai4j.openai4j=INFO
    #logging.level.dev.ai4j.mistral=DEBUG
