apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-product-catalog.fullname" . }}
  labels:
    {{- include "ai-product-catalog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Cluster
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
      protocol: TCP
  sessionAffinity: None
  selector:
    {{- include "ai-product-catalog.selectorLabels" . | nindent 4 }}
